[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "streamlit run web_scheduler.py --server.address 0.0.0.0 --server.port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[service]
ports = ["8501"] 